import { defineScenario } from "../src/scenario/index.ts"

export default defineScenario({
  id: "grand-battle",
  name: "Grand battle - the whole roster, at scale",
  notes:
    "The owner asked for one large, populous scenario to watch, separate from the small proof fixtures - this is that fixture, and it makes no rule claim the smaller ones do not already make. Extra-large-extra-wide (72x24), the largest preset the canon allows, with most of each faction's roster fielded in depth rather than in the single ranks the proof fixtures use: three Citizen files (troopers front, marksmen held back) either side of a Nexus and two barracks, against a Ravel swarm (runners and slingers in depth, four three-tile raiders, three fuelwagons) either side of a Nexus and two dens. The no-man's-land between the fronts is deliberately open ground: an early draft scattered small rock clusters there for texture, and with dozens of units retargeting constantly as the fight develops, several of them ended up walking straight at a rock on their own row or column and stalling for good - Q15's on-axis dead end, at scale. This fixture is for watching, not for proving a routing claim, so the terrain lost and the roster won.",

  grid: { preset: "extra-large-extra-wide" },
  seed: 0x0000C001,
  pulseTicks: 1440,

  terrain: [
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
    "........................................................................",
  ],
  terrainLegend: {
    ".": "terrain.plain",
    "#": "terrain.rock",
    "*": "terrain.deposit",
  },

  placements: [
    "                                                                        ",
    "                                                                        ",
    "                t                                    x                  ",
    "            m     t                                x      z             ",
    "    B       m                                             z      D      ",
    "                    t                            x                      ",
    "            m   t                                    x    z             ",
    "                  t                                x                    ",
    "                                                >                       ",
    "  w         m       t                            x        z          S  ",
    "    N    h                                             v         R      ",
    "         h                                      >                       ",
    "  w         m   t                                    x    z          S  ",
    "                                                       v                ",
    "                  t                                x                    ",
    "            m       t                            x        z             ",
    "                t                                    x                  ",
    "    B                                           >                D      ",
    "            m     t                                x      z             ",
    "                    t                                  v                ",
    "                                                >                       ",
    "            m   t                                x        z          S  ",
    "                                                                        ",
    "                                                                        ",
  ],
  placementLegend: {
    t: { player: "A", content: "unit.citizen.trooper" },
    m: { player: "A", content: "unit.citizen.marksman" },
    w: { player: "A", content: "unit.citizen.worker" },
    h: { player: "A", content: "unit.citizen.hauler" },
    N: { player: "A", content: "structure.citizen.nexus" },
    B: { player: "A", content: "structure.citizen.barracks" },
    x: { player: "B", content: "unit.ravel.runner" },
    z: { player: "B", content: "unit.ravel.slinger" },
    v: { player: "B", content: "unit.ravel.fuelwagon" },
    ">": { player: "B", content: "unit.ravel.raider" },
    S: { player: "B", content: "unit.ravel.scav" },
    R: { player: "B", content: "structure.ravel.nexus" },
    D: { player: "B", content: "structure.ravel.den" },
  },
})
