import { defineScenario } from "../src/scenario/index.ts"

export default defineScenario({
  id: "speed-parade",
  name: "Speed parade - every movement rate, side by side",
  notes:
    "A pure demonstration, not a rule proof: the owner asked to see units of different speeds moving side by side, so this lines up one of every mobile unit type from both rosters on a common starting column, all walking the same distance toward a lone static Grid Nexus, fastest at the top and slowest at the bottom. The target is a Nexus rather than a barracks on purpose - at 400 HP it outlasts the fastest arrivals long enough for the slower ones to actually get there too, rather than the demonstration ending the moment the first few units bring a 120-HP barracks down; its destruction still ends the Pulse if the parade runs long enough; pulseTicks is sized well past the slowest unit's crossing either way. Nothing here is a canon claim - movement rates on the fixture rosters are disposable bench content (AGENTS.md Section 2), tuned freely. Two changes made for this scenario also apply everywhere: the citizen trooper and marksman moved from 3/4 (16 ticks/step) to 1/1 (12 ticks/step) - the owner's other finding, that initial movement felt a little slow, and troopers/marksmen are the units most players spend the most time watching. Order, fastest to slowest at the rates now in play: scav (8 ticks/step), slinger (9), runner (10), worker/trooper/marksman (12, tied), raider (15), fuelwagon (18), hauler (24) - a three-fold spread from fastest to slowest, arriving in that order and then settling into whatever each one's weapon does to the Nexus.",

  grid: { preset: "medium-extra-wide" },
  seed: 0x0000D001,
  pulseTicks: 900,

  terrain: [
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
  ],
  terrainLegend: {
    ".": "terrain.plain",
    "#": "terrain.rock",
    "*": "terrain.deposit",
  },

  placements: [
    "                    S                           ",
    "                    z                           ",
    "                    x                           ",
    "                    w                           ",
    "                    t                           ",
    "                    m                           ",
    "                    r                           ",
    "                    v                           ",
    "                    h                           ",
    "                                                ",
    "                                                ",
    "                                                ",
    "                                          N     ",
    "                                                ",
    "                                                ",
    "                                                ",
  ],
  placementLegend: {
    S: { player: "A", content: "unit.ravel.scav" },
    z: { player: "A", content: "unit.ravel.slinger" },
    x: { player: "A", content: "unit.ravel.runner" },
    w: { player: "A", content: "unit.citizen.worker" },
    t: { player: "A", content: "unit.citizen.trooper" },
    m: { player: "A", content: "unit.citizen.marksman" },
    r: { player: "A", content: "unit.ravel.raider" },
    v: { player: "A", content: "unit.ravel.fuelwagon" },
    h: { player: "A", content: "unit.citizen.hauler" },
    N: { player: "B", content: "structure.citizen.nexus" },
  },
})
